add_newline = true

[character]
success_symbol = "[▲](bold)"
error_symbol = "[✗](red)"

[directory]
truncation_length = 80
truncate_to_repo = false
style = "white italic"

[git_branch]
style = "cyan"
symbol = " "

[swift]
format = ""

[lua]
format = ""

[nodejs]
format = ""

[package]
format = "[$symbol$version]($style) "
symbol = " "
