[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "0x585b70"
blue = "0x89b4fa"
cyan = "0x94e2d5"
green = "0xa6e3a1"
magenta = "0xf5c2e7"
red = "0xf38ba8"
white = "0xa6adc8"
yellow = "0xf9e2af"

[colors.cursor]
cursor = "0xd7d7d7"
text = "0x1e1e2e"

[colors.normal]
black = "0x45475a"
blue = "0x89b4fa"
cyan = "0x94e2d5"
green = "0xa6e3a1"
magenta = "0xf5c2e7"
red = "0xf38ba8"
white = "0xbac2de"
yellow = "0xf9e2af"

[colors.primary]
background = "0x1e2030"
foreground = "0xcdd6f4"

[colors.selection]
background = "0x585b70"
text = "0xcdd6f4"

[cursor.style]
blinking = "Off"
shape = "Block"

[font]
builtin_box_drawing = false
size = 14.3

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 1

[font.glyph_offset]
x = 0
y = 0

# [font.italic]
# family = "JuliaMono"
# style = "Italic"

# [font.bold]
# family = "JuliaMono"
# style = "Normal"


[[hints.enabled]]
command = "xdg-open"
post_processing = true
regex = "(magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-<>\"\\s{-}\\^⟨⟩`]+"

[hints.enabled.binding]
key = "U"
mods = "Control|Shift"

[hints.enabled.mouse]
enabled = true
mods = "Control"

[scrolling]
history = 5000
multiplier = 5

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[shell]
program = "/bin/zsh"

[window]
decorations = "buttonless" # "full"
dynamic_padding = false
dynamic_title = false
opacity = 1.0
title = "Alacritty"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.dimensions]
columns = 140
lines = 38

[window.padding]
x = 15
y = 10
